Bootstrap: docker
From: debian:latest

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://gitub.com/pscedu/singularity-wordgrinder
    COPYRIGHT Copyright © 2025 Pittsburgh Supercomputing Center. All Rights Reserved.  
    VERSION 0.8

%post
    apt update
    apt install -y wordgrinder

%runscript
    wordgrinder "$@"
